### ISSUE TITLE
[nits]interfaceに充てる変数名

### ISSUE THREAD

**Issue by NULL-header** [g00chy/js-plactice#4]
interfaceで使う変数名は大文字のIから始まるパスカルケースであるとよい。
なお、公式のドキュメントではinterfaceが型宣言でもあるからか通常のパスカルケースで変数名を割り当てている。

**Comment by kotarou1192** [comment]
https://typescript-jp.gitbook.io/deep-dive/styleguide#intfsu

https://saku.io/use-i-as-interface-prefix-in-typescript/

有用な議論のメモ

**Comment by g00chy** [comment]
パスカルケース取り込ませていただきます。
Iから開始するのは、typescriptコーディング規約および、現在のIDE環境的にそぐわない方法と考えたので取り込みなしとさせていただきます。
