### ISSUE TITLE
[MUST]セミコロン抜け

### ISSUE THREAD

**Issue by NULL-header** [g00chy/js-plactice#6]
https://github.com/g00chy/js-plactice/blob/1ef6b455a4bcb09daf7683873c1cfa601f52974f/jsprimer-cliapp/src/routes/index.ts#L4
ここはセミコロンが抜けているのに、他の行はセミコロンがあります。
自動挿入なりprettierなり入れましょう。

**Comment by g00chy** [comment]
@NULL-header ありがとうございます。
こちらを整理する段階で両方ともにprettierで対応していきます。
